// import { NextIntlClientProvider, hasLocale } from "next-intl";
// import { notFound } from "next/navigation";
// import { routing } from "@/i18n/routing";
// import LanguageSwitcher from "../../_components/language-switcher/LanguageSwitcher";
// import { Toaster } from "@/components/ui/sonner";
// import { isLoggedIn } from "@/lib/auth";
// import { redirect } from "next/navigation";
// import {
//   Breadcrumb,
//   BreadcrumbItem,
//   BreadcrumbLink,
//   BreadcrumbList,
//   BreadcrumbPage,
//   BreadcrumbSeparator,
// } from "@/components/ui/breadcrumb";
// import { Separator } from "@/components/ui/separator";
// import {
//   SidebarInset,
//   SidebarProvider,
//   SidebarTrigger,
// } from "@/components/ui/sidebar";
// import MainSidebar from "@/app/_components/main-sidebar/main-sidebar";
// // Fix this import path - go up 3 levels to reach app/_components
// import { LoadingProvider } from "@/app/_components/loading-provider/LoadingProvider";
// import "../../globals.css";

// export function generateStaticParams() {
//   return [{ locale: "en" }, { locale: "ar" }];
// }

// export const metadata = {
//   title: "Tashtri Dashboard",
//   description: "Generated by create next app",
// };

// export default async function DashboardLayout({
//   children,
//   params: paramsPromise,
// }) {
//   const params = await paramsPromise;
//   const { locale } = params;

//   if (!hasLocale(routing.locales, locale)) {
//     notFound();
//   }

//   const loggedIn = await isLoggedIn();

//   if (!loggedIn) {
//     redirect("/login");
//   }

//   return (
//     <html lang={locale}>
//       <body className="">
//         <LoadingProvider minimumLoadingTime={3000} showProgress={true}>
//           <NextIntlClientProvider locale={locale}>
//             <SidebarProvider>
//               <MainSidebar />
//               <SidebarInset>
//                 <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
//                   <div className="w-full flex items-center justify-between gap-2">
//                     <div className="flex items-center gap-2 px-4">
//                       <SidebarTrigger className="-ml-1" />
//                       <Separator
//                         orientation="vertical"
//                         className="mr-2 data-[orientation=vertical]:h-4"
//                       />
//                       <Breadcrumb>
//                         <BreadcrumbList>
//                           <BreadcrumbItem className="hidden md:block">
//                             <BreadcrumbLink href="#">
//                               Building Your Application
//                             </BreadcrumbLink>
//                           </BreadcrumbItem>
//                           <BreadcrumbSeparator className="hidden md:block" />
//                           <BreadcrumbItem>
//                             <BreadcrumbPage>Data Fetching</BreadcrumbPage>
//                           </BreadcrumbItem>
//                         </BreadcrumbList>
//                       </Breadcrumb>
//                     </div>

//                     <div className="px-4">
//                       <LanguageSwitcher
//                         currentLocale={locale}
//                         availableLocales={routing.locales}
//                       />
//                     </div>
//                   </div>
//                 </header>
//                 <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
//                   {children}
//                 </div>
//               </SidebarInset>
//             </SidebarProvider>
//             <Toaster position="top-center" />
//           </NextIntlClientProvider>
//         </LoadingProvider>
//       </body>
//     </html>
//   );
// }

// app/[locale]/(dashboard)/layout.js
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import LanguageSwitcher from "../../_components/language-switcher/LanguageSwitcher";
import { isLoggedIn } from "@/lib/auth";
import { redirect } from "next/navigation";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import MainSidebar from "@/app/_components/main-sidebar/main-sidebar";
import "../../globals.css";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ar" }];
}

export const metadata = {
  title: "Tashtri Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
  params: paramsPromise,
}) {
  const params = await paramsPromise;
  const { locale } = params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const loggedIn = await isLoggedIn();

  if (!loggedIn) {
    redirect("/login");
  }

  return (
    <SidebarProvider>
      <MainSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
          <div className="w-full flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator
                orientation="vertical"
                className="mr-2 data-[orientation=vertical]:h-4"
              />
              <Breadcrumb>
                <BreadcrumbList>
                  <BreadcrumbItem className="hidden md:block">
                    <BreadcrumbLink href="#">
                      Building Your Application
                    </BreadcrumbLink>
                  </BreadcrumbItem>
                  <BreadcrumbSeparator className="hidden md:block" />
                  <BreadcrumbItem>
                    <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                  </BreadcrumbItem>
                </BreadcrumbList>
              </Breadcrumb>
            </div>

            <div className="px-4">
              <LanguageSwitcher
                currentLocale={locale}
                availableLocales={routing.locales}
              />
            </div>
          </div>
        </header>
        <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}