import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import LanguageSwitcher from "../../_components/language-switcher/LanguageSwitcher";
import { Toaster } from "@/components/ui/sonner";
import { isLoggedIn } from "@/lib/auth";
import { redirect } from "next/navigation";
import Images from "../../../../public/assets/images/images";
import Image from "next/image";
import { LoadingProvider } from "@/app/_components/loading-provider/LoadingProvider";
import "../../globals.css";

export const metadata = {
  title: "Tashtri Dashboard",
  description: "Generated by create next app",
};

export default async function AuthLayout({ children, params: paramsPromise }) {
  const params = await paramsPromise;
  const { locale } = params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const loggedIn = await isLoggedIn();

  if (loggedIn) {
    redirect("/dashboard");
  }

  return (
    <html lang={locale}>
      <body
        className={`min-h-screen flex flex-col items-center justify-center bg-[#f7f7f8] relative`}
      >
        <LoadingProvider minimumLoadingTime={3000} showProgress={true}>
          <div className="flex gap-10 items-center justify-center absolute top-12 end-12">
            <div className="py-2.5 px-3 flex rounded-[6px] shadow-sm bg-white">
              <LanguageSwitcher
                currentLocale={locale}
                availableLocales={routing.locales}
              />
            </div>
          </div>
          <div className="mb-7">
            <Image src={Images.colorLogo} alt="logo" width={180} height={60} />
          </div>

          <NextIntlClientProvider locale={locale}>
            <div className="w-full max-w-md p-6 bg-white rounded-[12px]">
              {children}
            </div>
          </NextIntlClientProvider>
          <Toaster position="top-center" />
        </LoadingProvider>
      </body>
    </html>
  );
}
